version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'
  web:
    build: .
    links:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app